# Generated by Django 5.2.1 on 2025-06-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(verbose_name=False)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=50)),
                ('eliminado', models.BooleanField(verbose_name=False)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fechaCompra', models.DateField()),
                ('unidad', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(verbose_name=False)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.categories')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.supplier')),
            ],
        ),
    ]
