# Generated by Django 5.2.1 on 2025-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='categories',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
