# Generated by Django 5.2.1 on 2025-06-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_rawmaterial_precio_alter_categories_eliminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.units'),
        ),
    ]
