# Generated by Django 5.2.1 on 2025-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_units_alter_rawmaterial_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='precio',
            field=models.FloatField(),
        ),
    ]
