# Generated by Django 5.2.1 on 2025-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0005_rename_contacto_supplier_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='codigoTel',
            field=models.CharField(default='0412', max_length=10),
            preserve_default=False,
        ),
    ]
