# Generated by Django 5.2.1 on 2025-06-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0006_supplier_codigotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField()),
                ('cantidad', models.FloatField()),
                ('moneda', models.CharField(max_length=50)),
                ('tasa', models.IntegerField()),
                ('referencia', models.CharField(max_length=100)),
                ('eliminado', models.BooleanField(default=False)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='raw_material.supplier')),
            ],
        ),
    ]
