# Generated by Django 5.2.1 on 2025-06-22 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_paysupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('eliminado', models.BooleanField(default=False)),
                ('creacion', models.DateField(auto_now_add=True)),
                ('materiaPrima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencia', to='raw_material.rawmaterial')),
            ],
        ),
    ]
