# Generated by Django 5.2.1 on 2025-06-22 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0008_rawmaterialinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='materiaPrima',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='existencia', to='raw_material.rawmaterial'),
        ),
    ]
