# Generated by Django 5.2.1 on 2025-06-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0009_alter_rawmaterialinventory_materiaprima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='fechaCompra',
        ),
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='materiaPrima',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='raw_material.rawmaterial'),
        ),
    ]
