# Generated by Django 5.2.1 on 2025-06-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0010_remove_rawmaterial_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='factorBase',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='tipo',
            field=models.CharField(default='masa', max_length=100),
            preserve_default=False,
        ),
    ]
