# Generated by Django 5.2.1 on 2025-06-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0011_categories_factorbase_categories_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='factorBase',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='tipo',
        ),
        migrations.AddField(
            model_name='units',
            name='factorBase',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='units',
            name='tipo',
            field=models.CharField(default='masa', max_length=100),
            preserve_default=False,
        ),
    ]
