# Generated by Django 5.2.1 on 2025-06-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0012_remove_categories_factorbase_remove_categories_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
