# Generated by Django 5.2.1 on 2025-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0013_alter_rawmaterialinventory_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='precio',
        ),
        migrations.AddField(
            model_name='rawmaterialinventory',
            name='precio',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
