# Generated by Django 5.2.1 on 2025-06-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0014_remove_rawmaterial_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialinventory',
            name='materiaPrima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='raw_material.rawmaterial'),
        ),
    ]
